chore: Fix commit script

diff --git a/git_hooks/commit-msg b/git_hooks/commit-msg
--- a/git_hooks/commit-msg
+++ b/git_hooks/commit-msg
@@ -36,14 +36,21 @@ fi
 
 # Rule 5: Length Limitations
 subject_length=${#subject}
-body_length=$(echo "$body" | wc -m)
-if (( subject_length > 50 )) || (( body_length > 72 )); then
-    echo "ERROR: Commit message subject should not exceed 50 characters and body should not exceed 72 characters per line"
+if (( subject_length > 50 )); then
+    echo "ERROR: Commit message subject should not exceed 50 characters"
     exit 1
 fi
 
+while read -r line; do
+    line_length=${#line}
+    if (( line_length > 72 )); then
+        echo "ERROR: Each line of the commit message body should not exceed 72 characters"
+        exit 1
+    fi
+done <<< "$body"
+
 # Rule 6: Separate subject from body with a blank line
-if [[ -n $body ]] && [[ $message =~ ^.*\n\n.*$ ]]; then
+if [[ -n $body ]] && [[ ! $message =~ ^.*\n\n.*$ ]]; then
     echo "ERROR: Commit message body should be separated from the subject with a blank line"
     exit 1
 fi
